version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "GregoTeam#69!8--"
    healthcheck:
      test: ["CMD-SHELL", "curl -sk -u admin:'GregoTeam#69!8--' https://localhost:9200 >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      OPENSEARCH_USERNAME: "admin"
      OPENSEARCH_PASSWORD: "GregoTeam#69!8--"
      OPENSEARCH_SSL_VERIFICATIONMODE: "none"
    depends_on:
      - opensearch-node1

  vector:
    image: timberio/vector:0.49.0-alpine
    container_name: vector
    restart: unless-stopped
    ports:
      - "8686:8686"
    command: ["--config", "/etc/vector/vector.toml", "--watch-config"]
    volumes:
      - ../vector/config:/etc/vector:ro  # ✅ ИСПРАВЛЕННЫЙ ПУТЬ!
      - ../logs:/var/log:ro
    depends_on:
      opensearch-node1:
        condition: service_healthy

volumes:
  opensearch-data1: