version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=GregoTeam#69!8--
      - plugins.security.disabled=true
      - plugins.security.ssl.http.enabled=false
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=GregoTeam#69!8--
    depends_on:
      - opensearch-node1

  vector:
    image: timberio/vector:0.49.0-alpine
    container_name: vector
    restart: unless-stopped
    volumes:
      - ../vector/config/vector.toml:/etc/vector/vector.toml:ro
      - ../logs:/var/log:ro
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data1: