# Читаем новые строки из файлов в /var/log
[sources.app_logs]
type = "file"
include = ["/var/log/*.log"]
read_from = "beginning"

# Добавим поля и нормализуем timestamp
[transforms.enrich]
type   = "remap"
inputs = ["app_logs"]
source = '''
  .timestamp = format_timestamp!(now(), format: "%+")  # RFC3339
  .source = "file"
  .ingest = "vector"
'''

# Пишем в OpenSearch через elasticsearch sink (совместим)
[sinks.opensearch]
type      = "elasticsearch"
inputs    = ["enrich"]
endpoints = ["https://opensearch-node1:9200"]
auth.strategy = "basic"
auth.user     = "admin"
auth.password = "GregoTeam#69!8--"
tls.verify_certificate = false
api_version = "v8"          # чтобы Vector не гадал

# В 0.49 индекс задаётся в подсекции bulk
mode = "bulk"
[sinks.opensearch.bulk]
index = "app-logs-%Y.%m.%d"

# Для отладки — видно те же события в логе контейнера Vector
[sinks.console]
type = "console"
inputs = ["enrich"]
encoding.codec = "json"
